import "./globals.css";
import Navbar from "@/components/Navbar";
import Container from "@/components/Container";
import { Barlow_Condensed, Barlow } from "next/font/google";

// Google Fonts
const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata = {
  title: "Frontend Mentor | Space tourism website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${barlow.className} `}
      >
        <Navbar />
        <Container>{children}</Container>
      </body>
    </html>
  );
}
